import Link from 'next/link';
import Image from 'next/image';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — CraftedDay',
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="font-serif text-xl text-primary mb-4">{title}</h2>
      <div className="text-primary/80 text-base leading-relaxed space-y-3">{children}</div>
    </section>
  );
}

export default function Terms() {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <nav className="flex items-center justify-between px-8 py-6 max-w-3xl mx-auto w-full">
        <Link href="/" className="flex items-center gap-2.5">
          <Image src="/logo.png" alt="CraftedDay" width={28} height={28} className="opacity-90" />
          <span className="font-serif text-xl text-primary tracking-tight">CraftedDay</span>
        </Link>
      </nav>

      <main className="flex-1 px-6 pb-20 max-w-3xl mx-auto w-full">
        <h1 className="font-serif text-4xl text-primary mb-2 mt-8">Terms of Service</h1>
        <p className="text-muted text-sm mb-12">Effective date: April 20, 2026</p>

        <Section title="Acceptance of Terms">
          <p>
            These Terms of Service (&ldquo;Terms&rdquo;) govern your use of CraftedDay, operated by Bennett Levaton, DBA CraftedDay (&ldquo;we,&rdquo; &ldquo;our,&rdquo; or &ldquo;us&rdquo;). By downloading, installing, or using CraftedDay, you agree to be bound by these Terms. If you do not agree, do not use the app.
          </p>
        </Section>

        <Section title="Eligibility">
          <p>You must be at least 13 years old to use CraftedDay. By using the app, you represent that you meet this requirement. Users between 13 and 17 must have a parent or guardian review and agree to these Terms on their behalf.</p>
        </Section>

        <Section title="Accounts">
          <p>You must create an account to use CraftedDay. You are responsible for maintaining the security of your account and all activity that occurs under it. We use Clerk for authentication — creating an account is subject to Clerk&apos;s terms as well.</p>
          <p>You agree to provide accurate information and to keep it up to date. We reserve the right to suspend or terminate accounts that violate these Terms.</p>
        </Section>

        <Section title="Subscriptions and Billing">
          <p>CraftedDay offers a free tier and a premium subscription. Premium features — including daily AI-generated sessions and full personalization — require a paid subscription.</p>
          <p><strong className="font-medium">Pricing.</strong> The monthly subscription is $9.99 USD per month. If a free trial is offered, the trial period and post-trial price will be shown clearly on the purchase screen before you subscribe. Prices in other regions are set by Apple in your local currency and may differ.</p>
          <p><strong className="font-medium">Billing.</strong> Subscriptions are billed through the Apple App Store. Your Apple ID will be charged at the beginning of each billing period.</p>
          <p><strong className="font-medium">Auto-renewal.</strong> Subscriptions automatically renew at the same price unless you cancel at least 24 hours before the end of the current billing period. Renewal charges occur within 24 hours before the period ends.</p>
          <p><strong className="font-medium">Cancellation.</strong> You can cancel your subscription at any time through your iPhone&apos;s Settings app: Settings → [Your Name] → Subscriptions → CraftedDay → Cancel. Cancellation takes effect at the end of the current billing period; you retain access until then.</p>
          <p><strong className="font-medium">Refunds.</strong> All purchases are processed by Apple. Refund requests are subject to Apple&apos;s refund policies. We do not issue refunds directly.</p>
          <p><strong className="font-medium">Price changes.</strong> We may change subscription pricing with reasonable notice. Continued use of the app after a price change constitutes acceptance of the new price.</p>
        </Section>

        <Section title="Acceptable Use">
          <p>You agree to use CraftedDay only for lawful, personal, non-commercial purposes. You may not:</p>
          <ul className="list-disc list-inside space-y-1 pl-1">
            <li>Attempt to access, scrape, or copy content from the app in bulk</li>
            <li>Reverse engineer, decompile, or attempt to extract source code</li>
            <li>Use the app to harm, harass, or deceive others</li>
            <li>Circumvent any access controls or security features</li>
            <li>Use the app for any commercial purpose without our written consent</li>
          </ul>
        </Section>

        <Section title="Content and Intellectual Property">
          <p>All content generated by CraftedDay — including meditation scripts, audio, and AI-generated text — is provided for your personal use only. We retain all intellectual property rights in the app, its design, and generated content.</p>
          <p>Content you provide (prompts, check-in responses, notes) remains yours. By submitting it, you grant us a limited license to use it solely to provide and improve the service.</p>
        </Section>

        <Section title="Not Medical Advice">
          <p>CraftedDay is a wellness application intended for relaxation and mindfulness purposes only. It is <strong className="font-medium">not</strong> a medical device, clinical tool, or substitute for professional mental health care.</p>
          <p>Nothing in the app constitutes medical advice, diagnosis, or treatment. If you are experiencing a mental health crisis or medical emergency, please contact a qualified healthcare provider or call emergency services.</p>
        </Section>

        <Section title="Disclaimers">
          <p>THE APP IS PROVIDED &ldquo;AS IS&rdquo; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE APP WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS.</p>
          <p>We do not guarantee that AI-generated sessions will meet your specific expectations or produce any particular outcome.</p>
        </Section>

        <Section title="Limitation of Liability">
          <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, BENNETT LEVATON AND CRAFTEDDAY SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF OR INABILITY TO USE THE APP.</p>
          <p>OUR TOTAL LIABILITY TO YOU FOR ANY CLAIMS ARISING FROM THESE TERMS OR YOUR USE OF THE APP SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.</p>
        </Section>

        <Section title="Termination">
          <p>We may suspend or terminate your account at any time if you violate these Terms or engage in conduct that we reasonably believe is harmful to us, other users, or third parties.</p>
          <p>You may close your account at any time by contacting us at support@craftedday.com. Upon termination, your right to use the app ceases and we may delete your data in accordance with our Privacy Policy.</p>
        </Section>

        <Section title="Governing Law">
          <p>These Terms are governed by the laws of the State of California, without regard to its conflict of law provisions. Any disputes will be resolved in the courts of California.</p>
        </Section>

        <Section title="Changes to These Terms">
          <p>We may update these Terms from time to time. We will notify you of material changes by updating the effective date. Continued use of the app after changes constitutes acceptance of the updated Terms.</p>
        </Section>

        <Section title="Contact">
          <p>
            Questions about these Terms? Contact us at{' '}
            <a href="mailto:support@craftedday.com" className="text-accent underline underline-offset-2">support@craftedday.com</a>.
          </p>
          <p>Bennett Levaton, DBA CraftedDay — California, United States</p>
        </Section>
      </main>

      <footer className="border-t border-divider px-6 py-8">
        <div className="max-w-3xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4 text-sm text-muted">
          <span>© {new Date().getFullYear()} Bennett Levaton</span>
          <div className="flex items-center gap-6">
            <Link href="/privacy" className="hover:text-primary transition-colors">Privacy</Link>
            <Link href="/terms" className="hover:text-primary transition-colors">Terms</Link>
            <Link href="/support" className="hover:text-primary transition-colors">Support</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
